// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhHofI60k0FjtcEoYVDcrqo4ERDrgkK0',
    appId: '1:994917582362:android:c602d6259512b3811b73a3',
    messagingSenderId: '994917582362',
    projectId: 'dishlocal-dev',
    storageBucket: 'dishlocal-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIbp0CVdWSv4iwv8xYesIDiHA4b6-1JHI',
    appId: '1:994917582362:ios:4aff2a5aa4ccadd11b73a3',
    messagingSenderId: '994917582362',
    projectId: 'dishlocal-dev',
    storageBucket: 'dishlocal-dev.firebasestorage.app',
    androidClientId: '994917582362-0mvsihm07dnlecg4rj5rf908di9t5bb2.apps.googleusercontent.com',
    iosClientId: '994917582362-ujdqlafp24o6ort57e5qjtnrr0eko6hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishlocal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDmSODs0VWRkedqXQGNrl2VUnJ8ZLpqzc',
    appId: '1:994917582362:web:93e4c219766981b21b73a3',
    messagingSenderId: '994917582362',
    projectId: 'dishlocal-dev',
    authDomain: 'dishlocal-dev.firebaseapp.com',
    storageBucket: 'dishlocal-dev.firebasestorage.app',
    measurementId: 'G-8G6YKJX1NL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIbp0CVdWSv4iwv8xYesIDiHA4b6-1JHI',
    appId: '1:994917582362:ios:4aff2a5aa4ccadd11b73a3',
    messagingSenderId: '994917582362',
    projectId: 'dishlocal-dev',
    storageBucket: 'dishlocal-dev.firebasestorage.app',
    androidClientId: '994917582362-0mvsihm07dnlecg4rj5rf908di9t5bb2.apps.googleusercontent.com',
    iosClientId: '994917582362-ujdqlafp24o6ort57e5qjtnrr0eko6hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishlocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDmSODs0VWRkedqXQGNrl2VUnJ8ZLpqzc',
    appId: '1:994917582362:web:3d37fd16a826f5ee1b73a3',
    messagingSenderId: '994917582362',
    projectId: 'dishlocal-dev',
    authDomain: 'dishlocal-dev.firebaseapp.com',
    storageBucket: 'dishlocal-dev.firebasestorage.app',
    measurementId: 'G-B27R7BV1J3',
  );

}